#!/usr/bin/env python3
"""Render a compact human-readable preview from search_bib.py JSON output."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

ABSTRACT_LIMIT = 240
ANNOTATION_LIMIT = 160
KEYWORDS_LIMIT = 120
WHITESPACE_RE = re.compile(r"\s+")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a compact preview from search_bib.py JSON output."
    )
    parser.add_argument(
        "--input",
        help="Path to a JSON file generated by search_bib.py. Reads stdin when omitted.",
    )
    return parser.parse_args()


def normalize_text(value: Any) -> str:
    if value is None:
        return ""
    return WHITESPACE_RE.sub(" ", str(value)).strip()


def truncate_text(value: Any, limit: int) -> str:
    text = normalize_text(value)
    if not text or len(text) <= limit:
        return text
    return text[: max(0, limit - 3)].rstrip() + "..."


def load_payload(args: argparse.Namespace) -> dict[str, Any]:
    content = Path(args.input).read_text(encoding="utf-8") if args.input else sys.stdin.read()
    if not content.strip():
        raise ValueError("expected JSON input on stdin or via --input")

    payload = json.loads(content)
    if not isinstance(payload, dict):
        raise ValueError("preview input must be a JSON object")
    results = payload.get("results")
    if results is None or not isinstance(results, list):
        raise ValueError("preview input must contain a results list")
    meta = payload.get("meta")
    if meta is not None and not isinstance(meta, dict):
        raise ValueError("preview input meta must be an object when present")
    return payload


def render_simple_value(value: Any) -> str:
    if isinstance(value, list):
        items = [normalize_text(item) for item in value if normalize_text(item)]
        return ",".join(items) if items else "none"
    if isinstance(value, dict):
        parts = []
        for key in sorted(value):
            rendered = render_simple_value(value[key])
            if rendered != "none":
                parts.append(f"{key}={rendered}")
        return "{" + ", ".join(parts) + "}" if parts else "none"

    rendered = normalize_text(value)
    return rendered if rendered else "none"


def render_filter_summary(filters: Any) -> str:
    if not isinstance(filters, dict) or not filters:
        return "Filters: none"

    parts = []
    for key in sorted(filters):
        rendered = render_simple_value(filters[key])
        if rendered != "none":
            parts.append(f"{key}={rendered}")
    return "Filters: " + ("; ".join(parts) if parts else "none")


def render_flags(flags: Any) -> str:
    if not isinstance(flags, dict):
        return "none"
    names = [name for name in sorted(flags) if bool(flags[name])]
    return ", ".join(names) if names else "none"


def iter_citation_lines(citations: Any) -> Iterable[str]:
    if not isinstance(citations, dict):
        return []

    lines: list[str] = []
    latex = citations.get("latex")
    if isinstance(latex, dict):
        latex_parts = [
            normalize_text(latex.get("cite")),
            normalize_text(latex.get("parencite")),
            normalize_text(latex.get("textcite")),
        ]
        latex_parts = [part for part in latex_parts if part]
        if latex_parts:
            lines.append("  LaTeX: " + " | ".join(latex_parts))

    typst = citations.get("typst")
    if isinstance(typst, dict):
        typst_parts = [
            normalize_text(typst.get("inline")),
            normalize_text(typst.get("cite")),
        ]
        typst_parts = [part for part in typst_parts if part]
        if typst_parts:
            lines.append("  Typst: " + " | ".join(typst_parts))

    return lines


def render_entry(index: int, entry: dict[str, Any]) -> list[str]:
    key = normalize_text(entry.get("key")) or "<missing-key>"
    entry_type = normalize_text(entry.get("entry_type")) or "unknown"
    score = entry.get("score")
    if isinstance(score, (int, float)):
        score_text = f"{float(score):.4f}"
    else:
        score_text = normalize_text(score) or "n/a"

    lines = [
        f"{index}. {key} [{entry_type}] score={score_text} flags={render_flags(entry.get('flags'))}",
        f"  Title: {normalize_text(entry.get('title')) or '(untitled)'}",
        f"  Authors: {normalize_text(entry.get('author')) or '(unknown)'}",
    ]

    year = normalize_text(entry.get("year"))
    venue = normalize_text(entry.get("venue"))
    year_venue = " | ".join(part for part in (year, venue) if part) or "n/a"
    lines.append(f"  Year/Venue: {year_venue}")

    doi = normalize_text(entry.get("doi"))
    if doi:
        lines.append(f"  DOI: {doi}")

    eprint = normalize_text(entry.get("eprint"))
    if eprint:
        lines.append(f"  eprint: {eprint}")

    keywords = truncate_text(entry.get("keywords"), KEYWORDS_LIMIT)
    if keywords:
        lines.append(f"  Keywords: {keywords}")

    annotation = truncate_text(entry.get("annotation"), ANNOTATION_LIMIT)
    if annotation:
        lines.append(f"  Annotation: {annotation}")

    abstract = truncate_text(entry.get("abstract"), ABSTRACT_LIMIT)
    if abstract:
        lines.append(f"  Abstract: {abstract}")

    lines.extend(iter_citation_lines(entry.get("citations")))
    return lines


def render_preview(payload: dict[str, Any]) -> str:
    meta = payload.get("meta") or {}
    query = normalize_text(meta.get("query")) or "(none)"
    sort_mode = normalize_text(meta.get("sort")) or "relevance"
    results = payload.get("results") or []
    returned = meta.get("returned_entries", len(results))
    matched = meta.get("matched_entries", len(results))
    total = meta.get("total_entries", matched)

    lines = [
        f"Query: {query} | sort={sort_mode} | returned={returned} of {matched} matched ({total} total)",
        render_filter_summary(meta.get("applied_filters")),
    ]

    if not results:
        lines.append("Results: none")
        return "\n".join(lines)

    for idx, entry in enumerate(results, start=1):
        lines.append("")
        lines.extend(render_entry(idx, entry))
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    try:
        payload = load_payload(args)
        preview = render_preview(payload)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        raise SystemExit(2) from exc

    sys.stdout.write(preview)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
